apiVersion: apps/v1
kind: Deployment
metadata:
  name: vit-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vit-demo
  template:
    metadata:
      labels:
        app: vit-demo
    spec:
      containers:
        - name: vit-demo-container
          image:  254055089411.dkr.ecr.us-east-2.amazonaws.com/tanu-repo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000


